# Custom vars
# -------------------------

current_version:  1.0.0
name:         starplace.org

# Multiple languages
languages:          ['en', 'fr']
language_default:   'fr'
language:           'fr'

# Main Logo
# -------------------------

logo_regular: "media/logo/logo_regular.png"
logo_small_devices: "media/logo/logo_small.png"


# Main Navigation Links
# -------------------------

navbar_links:
  en:
    - title: "Home"
      url: "#image-hero"
    - title: "Features"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Work"
      url: "#work"
    - title: "Contact"
      url: "#contact"
  fr:
    - title: "Accueil"
      url: "#image-hero"
    - title: "DÃ©tails"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Travail"
      url: "#work"
    - title: "Contact"
      url: "#contact"

# Navigation Background Color.
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink
navbar_color: "starplace-orange"

# Image Hero
# -------------------------

title:
  en: "starplace.org"
  fr: "FRstarplace.org"

tagline:
  en: "taglines"
  fr: "FRtaglines"

# Features Thumbs
# -------------------------

features_thumbs:
  en:
    - title: "Clean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  fr:
    - title: "FRClean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."


# Blockquote
# -------------------------

blockquote:
  en:
     text: "We develop online marketing solutions that help enterprises accurately identify the consumers that truly need their services."
     tagline: "Serving the community since 2014"
     button_text: "Read More"
     button_url: "#_"
  fr:
     text: "FRWe develop online marketing solutions that help enterprises accurately identify the consumers that truly need their services."
     tagline: "Serving the community since 2014"
     button_text: "Read More"
     button_url: "#_"

# Services
# -------------------------

services:
  en:
   - title: "Front-End Development"
     icon: "desktop"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
  fr:
   - title: "FR_Front-End Development"
     icon: "desktop"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."

# Work Mosaic
# -------------------------

work_thumbs:
  en:
   - title: "Topps"
     description: "sss."
     url: "#_"
     image: "media/img/work-01.jpg"
   - title: "Veritatis Vel Recusandae"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-02.jpg"
   - title: "Consectetur Adipisicing"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-03.jpg"
   - title: "Asperiores Soluta"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-04.jpg"
   - title: "Officiis Aspernatur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-05.jpg"
   - title: "Soluta Asperiores"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-06.jpg"
   - title: "Adipisicing Consectetur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-07.jpg"
   - title: "Maxime Corporis Set"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-08.jpg"
  fr:
   - title: "FR_Topps"
     description: "sss."
     url: "#_"
     image: "media/img/work-01.jpg"
   - title: "Veritatis Vel Recusandae"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-02.jpg"
   - title: "Consectetur Adipisicing"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-03.jpg"
   - title: "Asperiores Soluta"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-04.jpg"
   - title: "Officiis Aspernatur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-05.jpg"
   - title: "Soluta Asperiores"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-06.jpg"
   - title: "Adipisicing Consectetur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-07.jpg"
   - title: "Maxime Corporis Set"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-08.jpg"

# Contact
# -------------------------

contact:
   latitude: "46.8939662"
   longitude: "-70.957640"
   marker_title: "starplace.org"
   marker_address: "6032 Chemin Royal, Saint-Laurent IO, Quebec, Canada"
   phone_number: "(581) 999-5408"
   email_address: "david@starplace.org"

# Configuration
# -------------------------

# Dependencies
highlighter:      false

# Permalinks
permalink:      none

# Server
destination:    ../dist
exclude:      [".gitignore", "Gruntfile.js", "node_modules", "package.json"]
port:         1984