# Custom vars
# -------------------------

current_version:  1.0.0
name:         starplace.org

# Main Logo
# -------------------------

logo_regular:       "media/logo/logo_regular.png"
logo_small_devices: "media/logo/logo_small.png"

# Main Navigation Links
# -------------------------

navbar_links:
  en:
    - title: "Home"
      url: "#image-hero"
    - title: "Features"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Work"
      url: "#work"
    - title: "Contact"
      url: "#contact"
  fr:
    - title: "Accueil"
      url: "#image-hero"
    - title: "Détails"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Travail"
      url: "#work"
    - title: "Contact"
      url: "#contact"

# Navigation Background Color.
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink, starplace-orange
navbar_color: "starplace-orange"

# Image Hero
# -------------------------

title:
  en: "starplace.org"
  fr: "FRstarplace.org"

tagline:
  en: ""
  fr: ""

# Features Thumbs
# -------------------------

features_thumbs:
  en:
    - title: "Clean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  fr:
    - title: "FRClean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."


# Blockquote
# -------------------------

blockquote:
  en:
     text: ""
     tagline: ""
     button_text: ""
     button_url: ""
  fr:
     text: ""
     tagline: ""
     button_text: ""
     button_url: ""

# Services
# -------------------------

services:
  en:
   - title: "Front-End Development"
     icon: "desktop"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
  fr:
   - title: "Applicatif web"
     icon: "desktop"
     description: "Gestionnaires de contenu, de clients, d'inventaire, je développe des applicatifs web sur mesure."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Analyse "

# Work Mosaic
# -------------------------

work_thumbs:
  en:
   - title: "Topps"
     description: ""
     url: "#_"
     image: "media/projects/toppsv2/toppsv2-small.jpg"
   - title: "Blobaland"
     description: ""
     url: "#_"
     image: "media/projects/blobaland/blobaland-small.jpg"
   - title: "Creaf"
     description: ""
     url: "#_"
     image: "media/projects/creaf/creaf-logo-thumb.jpg"
   - title: "FEPI"
     description: ""
     url: "#_"
     image: "media/projects/fepi/fepi-thumb.jpg"
   - title: "PIWB"
     description: ""
     url: "#_"
     image: "media/projects/piwb/piwb-thumb.jpg"
  fr:
   - title: "FR_Topps"
     description: "sss."
     url: "#_"
     image: "media/img/work-01.jpg"
   - title: "Veritatis Vel Recusandae"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-02.jpg"
   - title: "Consectetur Adipisicing"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-03.jpg"
   - title: "Asperiores Soluta"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-04.jpg"
   - title: "Officiis Aspernatur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-05.jpg"
   - title: "Soluta Asperiores"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-06.jpg"
   - title: "Adipisicing Consectetur"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-07.jpg"
   - title: "Maxime Corporis Set"
     description: "Fugit aut earum in sit, placeat quis consequatur."
     url: "#_"
     image: "media/img/work-08.jpg"

# Contact
# -------------------------

contact:
   latitude: "46.8939662"
   longitude: "-70.957640"
   marker_title: "starplace.org"
   marker_address: "6032 Chemin Royal, Saint-Laurent IO, Quebec, Canada"
   phone_number: "(581) 999-5408"
   email_address: "david@starplace.org"

# Configuration
# -------------------------

# Dependencies
highlighter:      false

# Permalinks
permalink:      none

# Server
destination:    ../dist
exclude:      [".gitignore", "Gruntfile.js", "node_modules", "package.json"]
port:         1984