# Custom vars
# -------------------------

current_version:  1.0.0
name:         starplace.org

# Main Logo
# -------------------------

logo_regular:       "media/logo/logo_regular.png"
logo_small_devices: "media/logo/logo_small.png"

# Main Navigation Links
# -------------------------

navbar_links:
  en:
    - title: "Home"
      url: "#image-hero"
    - title: "Features"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Work"
      url: "#work"
    - title: "Contact"
      url: "#contact"
  fr:
    - title: "Accueil"
      url: "#image-hero"
    - title: "Détails"
      url: "#features"
    - title: "Services"
      url: "#services"
    - title: "Travail"
      url: "#work"
    - title: "Contact"
      url: "#contact"

# Navigation Background Color.
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink, starplace-orange
navbar_color: "starplace-orange"

# Image Hero
# -------------------------

title:
  en: "starplace.org"
  fr: "FRstarplace.org"

tagline:
  en: "Welcome to starplace.org ! My name is David Grevink and I live on the Island of Orléans near Québec, Canada. I am a developer and designer and have been involved in computing for about 16 years now."
  fr: ""

# Features Thumbs
# -------------------------

features_thumbs:
  en:
    - title: "Clean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  fr:
    - title: "FRClean Code"
      icon: "code"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Build with Jekyll"
      icon: "flask"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Unique Design"
      icon: "file-image-o"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Responsive"
      icon: "mobile"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Easy Color Change"
      icon: "bolt"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "439 Icons"
      icon: "flag"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Google Maps"
      icon: "map-marker"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
    - title: "Fullscreen Background"
      icon: "expand"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."


# Blockquote
# -------------------------

blockquote:
  en:
     text: ""
     tagline: ""
     button_text: ""
     button_url: ""
  fr:
     text: ""
     tagline: ""
     button_text: ""
     button_url: ""

# Services
# -------------------------

services:
  en:
   - title: "Front-End Development"
     icon: "desktop"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
  fr:
   - title: "Applicatif web"
     icon: "desktop"
     description: "Gestionnaires de contenu, de clients, d'inventaire, je développe des applicatifs web sur mesure."
   - title: "iOS Development"
     icon: "apple"
     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
   - title: "UI/UX Design"
     icon: "magic"
     description: "Analyse "

# Work Mosaic
# -------------------------

work_thumbs:
  en:
   - title: "Topps"
     description: "Footballchecklist is a site all about collectible sport cards."
     url: "#_"
     image: "media/projects/toppsv2/toppsv2-small.jpg"
     detailed_image: "media/projects/toppsv2/toppsv2.jpg"
     detailed_description: "<h4>  Footballchecklist is about collectible football cards.</h4><p>  Footballchecklist was formerly known as Topps Football Collector. This is the second time Christian Joosten has contacted starplace about redesigning and programming his website.</p><h3>  Handling thousands of cards</h3><p> Handling and presenting the ever-growing card database was a top priority in the assignment, and fortunately the WebsitesApp content management system conceived by starplace has proven to be more than capable to handle the enormous amount of data on the site.</p><p>  Today, the website&#39;s card database has grown to almost 84500 cards, in 1423 decks spread across 18 brands.</p><h3>  Redesign</h3><p>  The new website design had to reflect the new direction Christian wanted his concept to take: more articles, more brands, search engine and social features.</p><p> Large stylish background, glass panels, clear database lists and powerful search engine capabilities were all integrated in the new site design.</p><h4>  Assignment details</h4><p>  Redesign, content management system, large database, search engine, blog and twitter integration, newsletter.</p><p>  <a href='http://footballchecklist.org/' target='_blank'>http://footballchecklist.org/</a></p>"
   - title: "Creaf.be Logo"
     description: "Nice logo for a Belgium-based photographer."
     url: "#_"
     image: "media/projects/creaf/creaf-logo-thumb.jpg"
     detailed_image: "media/projects/creaf/creaf.jpg"
     detailed_description: "<h4>Creaf.be logo design</h4><p>Commissioned in 2008 for his <a href='http://creaf.be/' target='_blank'>new site</a>.</p><h4>Assignment details</h4><p>Logo design.</p>"
   - title: "WebsitesApp"
     description: "Content Management System I have written under contract for Ideva Technologies Inc."
     url: "#_"
     image: "media/projects/websitesapp/websitesapp-thumb.jpg"
     detailed_image: "media/projects/websitesapp/websitesapp.jpg"
     detailed_description: "Content Management System I have written under contract for Ideva Technologies Inc."
   - title: "PIWB"
     description: "PIWB - Industrial history corporate site."
     url: "#_"
     image: "media/projects/piwb/piwb-thumb.jpg"
     detailed_image: "media/projects/piwb/piwb.jpg"
     detailed_description: "<h4>Patrimoine Industriel Wallonie-Bruxelles</h4><p>PIWB is a Belgium association for the preservation of historic industrial buildings.</p><h5>It was in 2007 that the long partnership between PIWB and starplace.org began.</h5><p>PIWB wanted a website to distribute and share their regular publications.</p><p>The website had to show what PIWB was all about: the preservation of historic industrial buildings.</p><p>Colors used had to be rust and tan.</p><p>During the course of the project, a new logo was also commissioned.</p><p><img src='media/projects/piwb/piwb-logo.jpg' style='width: 100%;' /></p><br/><h4>Content Management</h4><p>It was for PIWB that the first version of WebsitesApp, our content management system was first developed. It has now grown quite a bit and is now used in all our projects.</p><h4>Assignment details</h4><p>Design, logo design, custom content management and newsletter.</p><p><a href='http://patrimoineindustriel.be' target='_blank'>http://patrimoineindustriel.be</a></p>"
  fr:
   - title: "Topps"
     description: "Footballchecklist is a site all about collectible sport cards."
     url: "#_"
     image: "media/projects/toppsv2/toppsv2-small.jpg"
     detailed_image: "media/projects/toppsv2/toppsv2.jpg"
     detailed_description: "<h4>  Footballchecklist is about collectible football cards.</h4><p>  Footballchecklist was formerly known as Topps Football Collector. This is the second time Christian Joosten has contacted starplace about redesigning and programming his website.</p><h3>  Handling thousands of cards</h3><p> Handling and presenting the ever-growing card database was a top priority in the assignment, and fortunately the WebsitesApp content management system conceived by starplace has proven to be more than capable to handle the enormous amount of data on the site.</p><p>  Today, the website&#39;s card database has grown to almost 84500 cards, in 1423 decks spread across 18 brands.</p><h3>  Redesign</h3><p>  The new website design had to reflect the new direction Christian wanted his concept to take: more articles, more brands, search engine and social features.</p><p> Large stylish background, glass panels, clear database lists and powerful search engine capabilities were all integrated in the new site design.</p><h4>  Assignment details</h4><p>  Redesign, content management system, large database, search engine, blog and twitter integration, newsletter.</p><p>  <a href='http://footballchecklist.org/' target='_blank'>http://footballchecklist.org/</a></p>"
   - title: "Creaf.be Logo"
     description: "Nice logo for a Belgium-based photographer."
     url: "#_"
     image: "media/projects/creaf/creaf-logo-thumb.jpg"
     detailed_image: "media/projects/creaf/creaf.jpg"
     detailed_description: "<h4>Creaf.be logo design</h4><p>Commissioned in 2008 for his <a href='http://creaf.be/' target='_blank'>new site</a>.</p><h4>Assignment details</h4><p>Logo design.</p>"
   - title: "WebsitesApp"
     description: "Content Management System I have written under contract for Ideva Technologies Inc."
     url: "#_"
     image: "media/projects/websitesapp/websitesapp-thumb.jpg"
     detailed_image: "media/projects/websitesapp/websitesapp.jpg"
     detailed_description: "Content Management System I have written under contract for Ideva Technologies Inc."
   - title: "PIWB"
     description: "PIWB - Industrial history corporate site."
     url: "#_"
     image: "media/projects/piwb/piwb-thumb.jpg"
     detailed_image: "media/projects/piwb/piwb.jpg"
     detailed_description: "<h4>Patrimoine Industriel Wallonie-Bruxelles</h4><p>PIWB is a Belgium association for the preservation of historic industrial buildings.</p><h5>It was in 2007 that the long partnership between PIWB and starplace.org began.</h5><p>PIWB wanted a website to distribute and share their regular publications.</p><p>The website had to show what PIWB was all about: the preservation of historic industrial buildings.</p><p>Colors used had to be rust and tan.</p><p>During the course of the project, a new logo was also commissioned.</p><p><img src='media/projects/piwb/piwb-logo.jpg' style='width: 100%;' /></p><br/><h4>Content Management</h4><p>It was for PIWB that the first version of WebsitesApp, our content management system was first developed. It has now grown quite a bit and is now used in all our projects.</p><h4>Assignment details</h4><p>Design, logo design, custom content management and newsletter.</p><p><a href='http://patrimoineindustriel.be' target='_blank'>http://patrimoineindustriel.be</a></p>"

# Contact
# -------------------------

contact:
   latitude: "46.8939662"
   longitude: "-70.957640"
   marker_title: "starplace.org"
   marker_address: "6032 Chemin Royal, Saint-Laurent IO, Quebec, Canada"
   phone_number: "(581) 999-5408"
   email_address: "david@starplace.org"

# Configuration
# -------------------------

# Dependencies
highlighter:      false

# Permalinks
permalink:      none

# Server
destination:    ../dist
exclude:      [".gitignore", "Gruntfile.js", "node_modules", "package.json"]
port:         1984